"""Populate a Stripe sandbox with data so the source-stripe streams aren't empty.

Run against a *test* key only; the script refuses anything else.

    uv run python ingestion/seed_stripe.py --customers 40 --months 12

Two caveats worth knowing before you read the output:

1. Stripe won't let you backdate `created`. Every object lands at "now", so the
   only real historical signal is `subscription.start_date` (via
   `backdate_start_date`) plus a synthetic `metadata.seeded_at` this script
   spreads over the requested window for downstream models to use.
2. Test clocks — the one mechanism that does produce time-spread billing data —
   are deliberately not used. Objects generated by a test clock are omitted from
   Stripe's list endpoints unless the request filters on the clock, and the
   Airbyte connector doesn't, so none of it would reach Postgres.

Re-running adds more data rather than replacing it. Every object is tagged with
`metadata.seed_run` so you can tell runs apart.
"""

from __future__ import annotations

import argparse
import os
import random
import sys
import uuid
from collections import Counter
from collections.abc import Callable
from datetime import datetime, timedelta, timezone
from typing import Any, TypeVar

import stripe
from dotenv import load_dotenv

T = TypeVar("T")

# Shared test payment methods. See https://docs.stripe.com/testing.
PM_SUCCESS = "pm_card_visa"
PM_DISPUTE = "pm_card_createDispute"
PM_BYPASS_PENDING = "pm_card_bypassPending"  # funds land as `available`, not `pending`
PM_DECLINE = "pm_card_chargeDeclined"

FIRST_NAMES = [
    "Amara", "Bhavna", "Chen", "Diego", "Elif", "Farid", "Grace", "Hiroshi",
    "Ines", "Jonas", "Kavya", "Lucia", "Mateo", "Nadia", "Omar", "Priya",
    "Quinn", "Rohan", "Sofia", "Tomas", "Ugo", "Vera", "Wen", "Yara", "Zane",
]
LAST_NAMES = [
    "Adeyemi", "Bianchi", "Costa", "Dubois", "Eriksen", "Fischer", "Garcia",
    "Haddad", "Ivanov", "Jensen", "Kowalski", "Lindqvist", "Mensah", "Novak",
    "Okafor", "Petrov", "Rossi", "Silva", "Tanaka", "Ueda", "Varga", "Weber",
]
CITIES = [
    ("San Francisco", "CA", "94103", "US"),
    ("Austin", "TX", "78701", "US"),
    ("New York", "NY", "10012", "US"),
    ("Chicago", "IL", "60607", "US"),
    ("Seattle", "WA", "98101", "US"),
]

PLANS = [
    ("Starter", 1500, "month"),
    ("Growth", 4900, "month"),
    ("Scale", 19900, "month"),
    ("Growth Annual", 49900, "year"),
]
ONE_OFF_PRODUCTS = [
    ("Onboarding & Migration", 25000),
    ("Priority Support Add-on", 7500),
    ("Custom Integration", 120000),
]

counts: Counter[str] = Counter()


def _try(label: str, fn: Callable[[], T]) -> T | None:
    """Run a seeding step, logging and swallowing Stripe errors.

    Some objects (payouts, disputes, credit notes) depend on sandbox state we
    can't fully control, and one failure shouldn't abandon the rest of the seed.
    """
    try:
        result = fn()
    except stripe.StripeError as exc:
        print(f"  ! {label}: {exc.user_message or exc}", file=sys.stderr)
        return None
    counts[label] += 1
    return result


def _person(rng: random.Random) -> tuple[str, str]:
    name = f"{rng.choice(FIRST_NAMES)} {rng.choice(LAST_NAMES)}"
    slug = name.lower().replace(" ", ".")
    return name, f"{slug}.{rng.randrange(1000, 9999)}@example.com"


def _seeded_at(rng: random.Random, months: int) -> str:
    """A synthetic timestamp in the past, since Stripe's `created` can't be set."""
    days = rng.randrange(0, max(months, 1) * 30)
    return (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()


def build_catalog(run_id: str) -> tuple[list[Any], list[Any]]:
    """Create recurring and one-time products/prices. Fills products + prices."""
    recurring, one_off = [], []

    for name, amount, interval in PLANS:
        product = stripe.Product.create(
            name=f"{name} Plan",
            description=f"{name} tier, billed {'annually' if interval == 'year' else 'monthly'}.",
            metadata={"seed_run": run_id, "tier": name.split()[0].lower()},
        )
        price = stripe.Price.create(
            product=product.id,
            unit_amount=amount,
            currency="usd",
            recurring={"interval": interval},
            metadata={"seed_run": run_id},
        )
        recurring.append(price)
        counts["product"] += 1
        counts["price"] += 1

    for name, amount in ONE_OFF_PRODUCTS:
        product = stripe.Product.create(
            name=name, metadata={"seed_run": run_id}
        )
        one_off.append(
            stripe.Price.create(
                product=product.id,
                unit_amount=amount,
                currency="usd",
                metadata={"seed_run": run_id},
            )
        )
        counts["product"] += 1
        counts["price"] += 1

    # No metered price here. Since API version 2025-03-31.basil metered prices
    # must be backed by a Billing Meter, and meter events don't produce the
    # legacy usage records that the connector's `usage_records` stream reads —
    # so that stream stays empty either way.
    return recurring, one_off


def create_customer(rng: random.Random, run_id: str, months: int) -> Any:
    """Create a customer with an attached default card. Fills customers +
    payment_methods."""
    name, email = _person(rng)
    city, state, postal, country = rng.choice(CITIES)
    customer = stripe.Customer.create(
        name=name,
        email=email,
        description=f"Seeded customer ({run_id})",
        address={
            "line1": f"{rng.randrange(10, 999)} Market St",
            "city": city,
            "state": state,
            "postal_code": postal,
            "country": country,
        },
        metadata={"seed_run": run_id, "seeded_at": _seeded_at(rng, months)},
    )
    counts["customer"] += 1

    # Shared test PMs are cloned on attach, so read the new id back off the
    # response rather than reusing PM_SUCCESS.
    payment_method = stripe.PaymentMethod.attach(PM_SUCCESS, customer=customer.id)
    stripe.Customer.modify(
        customer.id,
        invoice_settings={"default_payment_method": payment_method.id},
    )
    counts["payment_method"] += 1
    return customer


def create_subscription(
    rng: random.Random, run_id: str, customer: Any, price: Any, months: int
) -> Any | None:
    """Fills subscriptions, subscription_items, invoices, invoice_line_items,
    and (through automatic payment) charges + balance_transactions."""
    params: dict[str, Any] = {
        "customer": customer.id,
        "items": [{"price": price.id}],
        "metadata": {"seed_run": run_id, "seeded_at": _seeded_at(rng, months)},
    }

    roll = rng.random()
    if roll < 0.2:
        # Trialing subscriptions produce a 0-amount invoice and a distinct status.
        params["trial_period_days"] = 14
    else:
        # Real historical signal: start_date lands in the past even though
        # `created` can't. Stripe caps this, so fall back on rejection.
        params["backdate_start_date"] = int(
            (datetime.now(timezone.utc) - timedelta(days=rng.randrange(30, 330)))
            .timestamp()
        )
        params["proration_behavior"] = "none"

    def _create() -> Any:
        try:
            return stripe.Subscription.create(**params)
        except stripe.InvalidRequestError:
            params.pop("backdate_start_date", None)
            params.pop("proration_behavior", None)
            return stripe.Subscription.create(**params)

    subscription = _try("subscription", _create)
    if subscription is None:
        return None

    # Churn, so the warehouse sees canceled alongside active.
    if rng.random() < 0.15:
        _try("subscription_canceled", lambda: stripe.Subscription.cancel(subscription.id))

    return subscription


def one_off_payment(
    rng: random.Random,
    run_id: str,
    customer: Any,
    months: int,
    payment_method: str = PM_SUCCESS,
) -> Any | None:
    """Fills payment_intents, charges, balance_transactions."""
    return _try(
        "payment_intent",
        lambda: stripe.PaymentIntent.create(
            amount=rng.randrange(5, 400) * 100,
            currency="usd",
            customer=customer.id,
            payment_method=payment_method,
            payment_method_types=["card"],
            confirm=True,
            off_session=True,
            description=rng.choice(
                ["Professional services", "Hardware bundle", "Annual license", "Setup fee"]
            ),
            metadata={"seed_run": run_id, "seeded_at": _seeded_at(rng, months)},
        ),
    )


def standalone_invoice(
    rng: random.Random, run_id: str, customer: Any, price: Any, months: int
) -> Any | None:
    """Fills invoice_items, plus another shape of invoice/invoice_line_items."""
    item = _try(
        "invoice_item",
        # The price goes under `pricing`; a top-level `price` is rejected.
        lambda: stripe.InvoiceItem.create(
            customer=customer.id,
            pricing={"price": price.id},
            quantity=rng.randrange(1, 4),
            metadata={"seed_run": run_id, "seeded_at": _seeded_at(rng, months)},
        ),
    )
    if item is None:
        return None

    def _bill() -> Any:
        invoice = stripe.Invoice.create(
            customer=customer.id,
            collection_method="charge_automatically",
            auto_advance=True,
            # Without this a standalone invoice ignores the pending item above
            # and finalizes empty.
            pending_invoice_items_behavior="include",
            metadata={"seed_run": run_id},
        )
        return stripe.Invoice.finalize_invoice(invoice.id)

    return _try("standalone_invoice", _bill)


def seed_discounts(run_id: str) -> None:
    """Fills coupons and promotion_codes."""
    for name, kwargs in [
        ("LAUNCH25", {"percent_off": 25.0, "duration": "repeating", "duration_in_months": 3}),
        ("WELCOME10", {"amount_off": 1000, "currency": "usd", "duration": "once"}),
        ("PARTNER50", {"percent_off": 50.0, "duration": "forever"}),
    ]:
        coupon = _try(
            "coupon",
            lambda name=name, kwargs=kwargs: stripe.Coupon.create(
                name=name, metadata={"seed_run": run_id}, **kwargs
            ),
        )
        if coupon is None:
            continue
        _try(
            "promotion_code",
            # Current API nests the target under `promotion`; a bare `coupon`
            # kwarg is rejected as an unknown parameter.
            lambda coupon=coupon, name=name: stripe.PromotionCode.create(
                promotion={"type": "coupon", "coupon": coupon.id},
                code=f"{name}{uuid.uuid4().hex[:4].upper()}",
                metadata={"seed_run": run_id},
            ),
        )


def seed_payouts(run_id: str) -> None:
    """Fills payouts.

    Needs settled funds, so this charges through PM_BYPASS_PENDING first — test
    charges otherwise sit in `pending` forever and a payout would be rejected.
    """
    for _ in range(3):
        _try(
            "balance_top_up",
            lambda: stripe.PaymentIntent.create(
                amount=250_00,
                currency="usd",
                payment_method=PM_BYPASS_PENDING,
                payment_method_types=["card"],
                confirm=True,
                description="Seed: make funds available for payout",
                metadata={"seed_run": run_id},
            ),
        )

    balance = stripe.Balance.retrieve()
    available = next(
        (b.amount for b in balance.available if b.currency == "usd"), 0
    )
    if available < 100:
        print("  ! payout: no available USD balance", file=sys.stderr)
        return

    _try(
        "payout",
        lambda: stripe.Payout.create(
            amount=min(available, 500_00),
            currency="usd",
            metadata={"seed_run": run_id},
        ),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--customers", type=int, default=40)
    parser.add_argument(
        "--months",
        type=int,
        default=12,
        help="Window for the synthetic metadata.seeded_at spread and backdated "
        "subscription start dates.",
    )
    parser.add_argument("--seed", type=int, default=42, help="RNG seed, for repeatable runs.")
    args = parser.parse_args()

    load_dotenv()
    api_key = os.getenv("STRIPE_CLIENT_SECRET")
    if not api_key:
        print("STRIPE_CLIENT_SECRET is not set.", file=sys.stderr)
        return 1
    if not api_key.startswith(("sk_test_", "rk_test_")):
        print(
            "Refusing to run: STRIPE_CLIENT_SECRET is not a test key. This script "
            "creates charges, refunds and disputes.",
            file=sys.stderr,
        )
        return 1

    stripe.api_key = api_key
    stripe.max_network_retries = 3  # absorbs the test-mode 25 req/s rate limit

    rng = random.Random(args.seed)
    run_id = uuid.uuid4().hex[:8]
    print(f"Seeding Stripe sandbox (run {run_id}, {args.customers} customers)...")

    recurring_prices, one_off_prices = build_catalog(run_id)
    seed_discounts(run_id)

    charges_to_refund: list[str] = []

    for index in range(args.customers):
        customer = create_customer(rng, run_id, args.months)

        # ~65% subscribe; a quarter of those later add a second plan, so
        # subscription_items has rows beyond one-per-subscription.
        if rng.random() < 0.65:
            price = rng.choice(recurring_prices)
            subscription = create_subscription(rng, run_id, customer, price, args.months)
            if subscription is not None and rng.random() < 0.25:
                addon = rng.choice([p for p in recurring_prices if p.id != price.id])
                _try(
                    "subscription_item_addon",
                    lambda subscription=subscription, addon=addon: stripe.SubscriptionItem.create(
                        subscription=subscription.id,
                        price=addon.id,
                        proration_behavior="none",
                        metadata={"seed_run": run_id},
                    ),
                )

        # ~50% also buy something one-off.
        if rng.random() < 0.5:
            intent = one_off_payment(rng, run_id, customer, args.months)
            # stripe-python v12 objects are not dicts; use attribute access.
            if intent is not None and intent.latest_charge:
                charges_to_refund.append(intent.latest_charge)

        # ~20% get a manually assembled invoice.
        if rng.random() < 0.2:
            standalone_invoice(
                rng, run_id, customer, rng.choice(one_off_prices), args.months
            )

        # A couple of failed payments, for realism in the funnel.
        if rng.random() < 0.08:
            one_off_payment(rng, run_id, customer, args.months, payment_method=PM_DECLINE)

        # A couple of disputes. Stripe creates the dispute asynchronously.
        if index < 2:
            _try(
                "setup_intent",
                lambda: stripe.SetupIntent.create(
                    customer=customer.id,
                    payment_method=PM_SUCCESS,
                    payment_method_types=["card"],
                    confirm=True,
                    usage="off_session",
                    metadata={"seed_run": run_id},
                ),
            )
            one_off_payment(rng, run_id, customer, args.months, payment_method=PM_DISPUTE)

        if (index + 1) % 10 == 0:
            print(f"  ... {index + 1}/{args.customers} customers")

    # Refund a slice of the successful charges. Fills refunds.
    for charge_id in rng.sample(
        charges_to_refund, k=min(len(charges_to_refund), max(1, len(charges_to_refund) // 5))
    ):
        _try(
            "refund",
            lambda charge_id=charge_id: stripe.Refund.create(
                charge=charge_id,
                reason="requested_by_customer",
                metadata={"seed_run": run_id},
            ),
        )

    seed_payouts(run_id)

    print(f"\nDone (run {run_id}). Created:")
    for label, count in sorted(counts.items()):
        print(f"  {count:>5}  {label}")
    print("\nNow pull it into Postgres: make sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
