cubes:
  - name: products
    sql_table: public.products
    data_source: default

    joins: []

    dimensions:
      - name: product_id
        sql: "{CUBE}.product_id"
        type: string
        primary_key: true

      - name: product_category_name
        sql: "{CUBE}.product_category_name"
        type: string

      - name: product_photos_qty
        sql: "{CUBE}.product_photos_qty"
        type: string

      - name: product_weight_g
        sql: "{CUBE}.product_weight_g"
        type: string

    measures:
      - name: count
        type: count

      # Weight
      - name: avg_product_weight
        sql: "{CUBE}.product_weight_g"
        type: avg

      - name: min_product_weight
        sql: "{CUBE}.product_weight_g"
        type: min

      - name: max_product_weight
        sql: "{CUBE}.product_weight_g"
        type: max

      # Length
      - name: avg_product_length
        sql: "{CUBE}.product_length_cm"
        type: avg

      - name: min_product_length
        sql: "{CUBE}.product_length_cm"
        type: min

      - name: max_product_length
        sql: "{CUBE}.product_length_cm"
        type: max

      # Height
      - name: avg_product_height
        sql: "{CUBE}.product_height_cm"
        type: avg

      - name: min_product_height
        sql: "{CUBE}.product_height_cm"
        type: min

      - name: max_product_height
        sql: "{CUBE}.product_height_cm"
        type: max

      # Width
      - name: avg_product_width
        sql: "{CUBE}.product_width_cm"
        type: avg

      - name: min_product_width
        sql: "{CUBE}.product_width_cm"
        type: min

      - name: max_product_width
        sql: "{CUBE}.product_width_cm"
        type: max

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
